spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i10a701.p.ssafy.io:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    properties:
      hibernate:
        show_sql: true #만들어진 sql 보여줌
        format_sql: true #sql 가독성 좋게 보여줌
    hibernate:
      ddl-auto: update
#      ddl-auto: create #db 초기화 전략. 기존 테이블 삭제 후 생성
    database-platform: org.hibernate.dialect.MySQLDialect
  security: # OAuth2
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            redirect-uri: https://i10a701.p.ssafy.io/login/oauth2/code/naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, profile_image, email
            client-name: kakao-login
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            redirect-uri: https://i10a701.p.ssafy.io/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  main:
    allow-circular-references: true
server:
  port: 8081


#grpc:
#  server:
#    port: 9090
#    address: 0.0.0.0

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
  swagger-ui:
    path: /api/user/swagger-ui.html
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/

logging:
  level:
    org:
      springframework:
        security: DEBUG


jwt:
  secretKey: ${JWT_SECRETKEY}
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh